---
layout: cv
title: Hesron Kija's Resume
---

# Hesron Kija
Computer Science Student, Brigham Young University - Idaho

<div id="webaddress">
<a href="mailto:kij23001@byui.edu">kij23001@byui.edu</a>
| <a href="https://linkedin.com/in/hesron-kija">LinkedIn Profile</a>
</div>

## Summary

Computer Science student with a strong foundation in Python, JavaScript, C#, Java, and SQL, and hands-on experience in biomedical equipment engineering. Proven ability to lead teams, solve technical problems, and deliver measurable results. Seeking a campus job to apply technical skills and contribute to innovative projects.

## Education

`April 2023 - Present`
__Brigham Young University - Idaho, Rexburg, ID__
- BS, Computer Science
- Relevant coursework: Python, Teamwork, and Growth & Grit

`October 2019 - July 2022`
__Dar es Salaam Institute of Technology, Dar es Salaam, Tanzania__
- Dip, Biomedical Equipment Engineering
- Relevant coursework: Calculus, Teamwork, Communication, and Business Management

## Work Experience

`September 2023 - Present`
__Student Testing Center Proctor__
Student Testing Center | Brigham Young University - Idaho, Rexburg, ID
- Supervising students during examinations, ensuring adherence to testing policies and preventing academic dishonesty.
- Preparing and distributing testing materials, managing an organized and efficient testing environment.
- Addressing and resolving student inquiries and technical issues during exams, ensuring a smooth testing process.

`April 2023 - July 2023`
__Early Morning Custodian__
Student Health Center | Brigham Young University - Idaho, Rexburg, ID
- Teamwork and role-playing.
- Cleaning and maintaining the Student Health Center.
- Solid time management required.

## Skills

- Programming Languages: Python, JavaScript, C#, Java, SQL
- Soft Skills: Time management, Decision making, Organizational skills with attention to detail, Multitasking, Effective team collaboration
- Tools: Microsoft Office Suite

## Experiential Learning Projects

`August 2021 - October 2021`
__Biomedical Technician Assistant__
Industrial Practical Training | Muhimbili National Hospital, Dar es Salaam, Tanzania
- Led a team of 5 technicians to repair and maintain 50+ medical devices, reducing equipment downtime by 30% and improving patient care efficiency.
- Conducted monthly preventive maintenance, ensuring 100% compliance with safety standards.
- Created comprehensive medical device inventories for hospital wards, ensuring efficient tracking and accessibility throughout the three months.
- Performed monthly Planned Preventive Maintenance (PPM) for medical devices throughout the three months.

## Extra-curriculars

- Developed a Google Chrome extension during the Utah State University Hackathon, enabling users to access detailed website information through collaborative team efforts.
- Mentored students as part of the Heber J. Grant Peer Mentor Program, offering academic and personal guidance to enhance performance and goal achievement.
